version: "3"
services:
  ahem-ssr:
    image: o4oren/ahem:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "4000:4000"
    command: ["node", "dist/universalServer"]
    tty: true
    networks:
      - net1
    depends_on:
      - mongodb
    environment:
      serverBaseUri: elliott-king-ad-hoc-email-server---master.dev.ship.surf
      mongoConnectUrl: mongodb://mongodb:27017/
      appListenPort: 3000
      smtpPort: 2525
      allowAutocomplete: "true"
      allowedDomains: elliott-king-ad-hoc-email-server---master.dev.ship.surf
      jwtSecret: AH3M 709 S3cR3T

  ahem:
    image: o4oren/ahem:latest
    build:
      context: .
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "3000:3000"
      - "25:2525"
    tty: true
    networks:
      - net1
    depends_on:
      - mongodb
    environment:
      serverBaseUri: elliott-king-ad-hoc-email-server---master.dev.ship.surf
      mongoConnectUrl: mongodb://mongodb:27017/
      appListenPort: 3000
      smtpPort: 2525
      allowAutocomplete: "true"
      allowedDomains: elliott-king-ad-hoc-email-server---master.dev.ship.surf
      jwtSecret: AH3M 709 S3cR3T

  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - net1
networks:
  net1:
